//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVEL.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRAVEL.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] particulars of field operations.
        /// </summary>
        public static string _2_heading {
            get {
                return ResourceManager.GetString("2_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household’s last month consumption expenditure (in Rs.) .
        /// </summary>
        public static string _4_1_col_1 {
            get {
                return ResourceManager.GetString("4_1_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [4.1] household characteristics .
        /// </summary>
        public static string _4_1_heading {
            get {
                return ResourceManager.GetString("4_1_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. of hh member .
        /// </summary>
        public static string _5_1_col_1 {
            get {
                return ResourceManager.GetString("5_1_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usual time of leaving for educational institution from origin .
        /// </summary>
        public static string _5_1_col_2 {
            get {
                return ResourceManager.GetString("5_1_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 5.1: Details of usual trips to and from educational institution (pertaining to basic course) for persons of age of 6 years and above who are attending basic course in-person (i.e., with code 4 in col. 8 of Block 3 and code 2 in col. 9 of Block 3) .
        /// </summary>
        public static string _5_1_heading {
            get {
                return ResourceManager.GetString("5_1_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for code other than 9 in col. 8, whether having season ticket/pass/free pass for bus/rail as on the date of survey  (yes-1, no-2) .
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code 1 in col. 11, status of season tickets / pass for rail / bus (rail pass-1, bus pass-2, both–3) .
        /// </summary>
        public static string _if {
            get {
                return ResourceManager.GetString("if", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age (years).
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Companion.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorickshaw/ Toto/ e-rickshaw .
        /// </summary>
        public static string Autorickshaw {
            get {
                return ResourceManager.GetString("Autorickshaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorickshaw/ Toto/ e-rickshaw.
        /// </summary>
        public static string AutorickshawTotoerickshaw {
            get {
                return ResourceManager.GetString("AutorickshawTotoerickshaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time taken to reach workplace (in minutes).
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average time taken to reach the destination (in minutes) .
        /// </summary>
        public static string average12 {
            get {
                return ResourceManager.GetString("average12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average monthly cost of travel (Rs.) .
        /// </summary>
        public static string average2 {
            get {
                return ResourceManager.GetString("average2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average time taken to reach destination (in minutes)  .
        /// </summary>
        public static string average3 {
            get {
                return ResourceManager.GetString("average3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average monthly cost of travel (Rs.) .
        /// </summary>
        public static string average4 {
            get {
                return ResourceManager.GetString("average4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bicycle  .
        /// </summary>
        public static string bicycle {
            get {
                return ResourceManager.GetString("bicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bicycle .
        /// </summary>
        public static string bicycle1 {
            get {
                return ResourceManager.GetString("bicycle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 3: Demographic particulars of the household .
        /// </summary>
        public static string block_3_heading {
            get {
                return ResourceManager.GetString("block_3_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. of hh member(as in col. 1,block 3).
        /// </summary>
        public static string block_5_2_1 {
            get {
                return ResourceManager.GetString("block_5_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether return trip performed (yes-1, no-2).
        /// </summary>
        public static string block_5_2_10 {
            get {
                return ResourceManager.GetString("block_5_2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code 2 in both col.3 and col.10, destination is home (yes-1, no-2).
        /// </summary>
        public static string block_5_2_11 {
            get {
                return ResourceManager.GetString("block_5_2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown).
        /// </summary>
        public static string block_5_2_12 {
            get {
                return ResourceManager.GetString("block_5_2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destination [for code 1 in col. 10 copy the entry in cols. 4 to col. 6 to cols. 12 to 14].
        /// </summary>
        public static string block_5_2_12_head {
            get {
                return ResourceManager.GetString("block_5_2_12_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT(code).
        /// </summary>
        public static string block_5_2_13 {
            get {
                return ResourceManager.GetString("block_5_2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col.  12.
        /// </summary>
        public static string block_5_2_13_head {
            get {
                return ResourceManager.GetString("block_5_2_13_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string block_5_2_14 {
            get {
                return ResourceManager.GetString("block_5_2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance from origin to educational institution(kms).
        /// </summary>
        public static string block_5_2_15 {
            get {
                return ResourceManager.GetString("block_5_2_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance from educational institution to destination (kms)[for code 1 in col. 10 copy the entry in col. 15 to col. 16 ].
        /// </summary>
        public static string block_5_2_16 {
            get {
                return ResourceManager.GetString("block_5_2_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code 2 in col.10 and code 2 in col.11, purpose of trip from educational institution to destination.
        /// </summary>
        public static string block_5_2_17 {
            get {
                return ResourceManager.GetString("block_5_2_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip srl. no. .
        /// </summary>
        public static string block_5_2_2 {
            get {
                return ResourceManager.GetString("block_5_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origin is home (yes-1, no-2).
        /// </summary>
        public static string block_5_2_3 {
            get {
                return ResourceManager.GetString("block_5_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown).
        /// </summary>
        public static string block_5_2_4 {
            get {
                return ResourceManager.GetString("block_5_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origin .
        /// </summary>
        public static string block_5_2_4_head {
            get {
                return ResourceManager.GetString("block_5_2_4_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT(code).
        /// </summary>
        public static string block_5_2_5 {
            get {
                return ResourceManager.GetString("block_5_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col.  4.
        /// </summary>
        public static string block_5_2_5_head {
            get {
                return ResourceManager.GetString("block_5_2_5_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string block_5_2_6 {
            get {
                return ResourceManager.GetString("block_5_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown).
        /// </summary>
        public static string block_5_2_7 {
            get {
                return ResourceManager.GetString("block_5_2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to educational institution.
        /// </summary>
        public static string block_5_2_7_head {
            get {
                return ResourceManager.GetString("block_5_2_7_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT(code).
        /// </summary>
        public static string block_5_2_8 {
            get {
                return ResourceManager.GetString("block_5_2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col.7.
        /// </summary>
        public static string block_5_2_8_head {
            get {
                return ResourceManager.GetString("block_5_2_8_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether return trip performed (yes-1, no-2).
        /// </summary>
        public static string block_5_2_9 {
            get {
                return ResourceManager.GetString("block_5_2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 5.2: Details of within-day-trips in a travel day closest to the date of survey in the travel reference period (90 travel days) to and from educational institution for persons of age of 6 years and above who are attending basic course in-person (i.e., with code 04 in col. 8 of Block 3 and code 2 in col. 9 of Block 3 and code 1 in col. 12 of Block 5.1).
        /// </summary>
        public static string block_5_2_head {
            get {
                return ResourceManager.GetString("block_5_2_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [10] remarks by investigator (SE/ JSO) .
        /// </summary>
        public static string Block10 {
            get {
                return ResourceManager.GetString("Block10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [11] comments by supervisory officer(s) .
        /// </summary>
        public static string Block11 {
            get {
                return ResourceManager.GetString("Block11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primary mode of transport (code).
        /// </summary>
        public static string block5_10 {
            get {
                return ResourceManager.GetString("block5_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code between ‘41’ to ‘81’ excluding ‘43’ in col. 10,secondary mode of transport (code)[record code 09 if secondary mode of transport is not used].
        /// </summary>
        public static string block5_11 {
            get {
                return ResourceManager.GetString("block5_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average monthly cost of travel.
        /// </summary>
        public static string block5_9 {
            get {
                return ResourceManager.GetString("block5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average time taken to reach educational institution (in minutes).
        /// </summary>
        public static string block5_average {
            get {
                return ResourceManager.GetString("block5_average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to educational institution to destination.
        /// </summary>
        public static string block5_education {
            get {
                return ResourceManager.GetString("block5_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 5.1: Details of usual trips to and from educational institution (pertaining to basic course) for persons of age of 6 years and above who are attending basic course in-person (i.e., with code 4 in col. 8 of Block 3 and code 2 in col. 9 of Block 3) .
        /// </summary>
        public static string block5_head {
            get {
                return ResourceManager.GetString("block5_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code between ‘41’ to ‘81’ excluding ‘43’ in col. 5 secondary mode of transport (code).
        /// </summary>
        public static string block5_if {
            get {
                return ResourceManager.GetString("block5_if", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usual time of leaving for destination from educational institution.
        /// </summary>
        public static string block5_leving {
            get {
                return ResourceManager.GetString("block5_leving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online attendance at educational institution from home (number of days in last 7 days prior to the travel day).
        /// </summary>
        public static string block5_online {
            get {
                return ResourceManager.GetString("block5_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origin to educational institution .
        /// </summary>
        public static string block5_origin {
            get {
                return ResourceManager.GetString("block5_origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average time taken to reach destination (in minutes).
        /// </summary>
        public static string block5_reach {
            get {
                return ResourceManager.GetString("block5_reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. of hh member(as in col. 1, block 3) .
        /// </summary>
        public static string block5_srl {
            get {
                return ResourceManager.GetString("block5_srl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primary mode of transport (code).
        /// </summary>
        public static string block5_transport {
            get {
                return ResourceManager.GetString("block5_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average monthly cost of travel(Rs.).
        /// </summary>
        public static string block5_travel {
            get {
                return ResourceManager.GetString("block5_travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usual time of leaving for educational institution from origin(hh:mm in 24 hrs format).
        /// </summary>
        public static string block5_usual {
            get {
                return ResourceManager.GetString("block5_usual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether travelled to and from educational institution on at least one travel day during the travel reference period of last 90 travel days(yes-1, no-2).
        /// </summary>
        public static string block5_whether {
            get {
                return ResourceManager.GetString("block5_whether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 5.2: Details of within-day-trips in a travel day closest to the date of survey in the travel reference period (90 travel days) to and from educational institution for persons of age of 6 years and above who are attending basic course in-person (i.e., with code 04 in col. 8 of Block 3 and code 2 in col. 9 of Block 3 and code 1 in col. 12 of Block 5.1) .
        /// </summary>
        public static string Block52 {
            get {
                return ResourceManager.GetString("Block52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 6.1: Details of trips to and from fixed workplace that are of usual nature for persons of age of 15 years and above having fixed place of work (i.e., code 1 in col. 10 of Block 3) .
        /// </summary>
        public static string Block6_1 {
            get {
                return ResourceManager.GetString("Block6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 6.2: Details of within-day-trips in the travel day prior to the date of survey in the travel reference period (1 travel day) to and from fixed workplace for persons of age of 15 years and above having fixed place of work (i.e., code 1 in col. 10 of Block 3 and code 1 in col. 13 of Block 6.1) .
        /// </summary>
        public static string Block6_2 {
            get {
                return ResourceManager.GetString("Block6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. of hh member (as in col. 1, block 3).
        /// </summary>
        public static string block7_1 {
            get {
                return ResourceManager.GetString("block7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip srl. no. .
        /// </summary>
        public static string block7_2 {
            get {
                return ResourceManager.GetString("block7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance from origin to destination (kms).
        /// </summary>
        public static string block7_2_10 {
            get {
                return ResourceManager.GetString("block7_2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time of leaving for destination from origin (hh:mm in 24 hrs format).
        /// </summary>
        public static string block7_2_11 {
            get {
                return ResourceManager.GetString("block7_2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average time taken to reach the destination (in minutes).
        /// </summary>
        public static string block7_2_12 {
            get {
                return ResourceManager.GetString("block7_2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primary mode of transport (code).
        /// </summary>
        public static string block7_2_13 {
            get {
                return ResourceManager.GetString("block7_2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost of trip(Rs.).
        /// </summary>
        public static string block7_2_14 {
            get {
                return ResourceManager.GetString("block7_2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether return trip performed (yes-1, no-2).
        /// </summary>
        public static string block7_2_9 {
            get {
                return ResourceManager.GetString("block7_2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown).
        /// </summary>
        public static string block7_3 {
            get {
                return ResourceManager.GetString("block7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT(code).
        /// </summary>
        public static string block7_4 {
            get {
                return ResourceManager.GetString("block7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col. 3.
        /// </summary>
        public static string block7_4_head {
            get {
                return ResourceManager.GetString("block7_4_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string block7_5 {
            get {
                return ResourceManager.GetString("block7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown).
        /// </summary>
        public static string block7_6 {
            get {
                return ResourceManager.GetString("block7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col. 6.
        /// </summary>
        public static string block7_7_head {
            get {
                return ResourceManager.GetString("block7_7_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 7: Details of within-day-trips in the travel day prior to the date of survey in the travel reference period (1 travel day) to non-fixed place of work for persons of age of 15 years and above* with code 1, 2 &amp; 3 in col. 8 of Block 3 .
        /// </summary>
        public static string block7_head {
            get {
                return ResourceManager.GetString("block7_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 8: Details of within-day-trips in the travel-day prior to the date of survey in the travel reference period (1 travel day) by household members of age 6 years and above for any purpose excluding work and attending educational institution (as already captured in Block 6.1 to Block 7) .
        /// </summary>
        public static string Block8 {
            get {
                return ResourceManager.GetString("Block8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 8.1: Purpose of the trip for each household member of age 6 years and above for within-day trips undertaken in the travel day prior to the date of survey (as recorded in Block 8) .
        /// </summary>
        public static string Block81 {
            get {
                return ResourceManager.GetString("Block81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip srl. no. .
        /// </summary>
        public static string block9_1 {
            get {
                return ResourceManager.GetString("block9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether return trip performed (yes-1, no-2.
        /// </summary>
        public static string block9_10 {
            get {
                return ResourceManager.GetString("block9_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no. of hh members in the trip.
        /// </summary>
        public static string block9_2 {
            get {
                return ResourceManager.GetString("block9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purpose of the trip .
        /// </summary>
        public static string block9_3 {
            get {
                return ResourceManager.GetString("block9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 9: Details of overnight trips undertaken by the household members during all the travel-days in the travel reference period (28 travel days).
        /// </summary>
        public static string block9_head {
            get {
                return ResourceManager.GetString("block9_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no. of overnight trips performed by the household in the last 28 travel days prior to the date of survey (return trip will be counted as separate trip).
        /// </summary>
        public static string block9_head_1 {
            get {
                return ResourceManager.GetString("block9_head_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block 9.1: Details of overnight trips by purpose undertaken by the household members during all the travel-days in the travel reference period (28 travel days) (to be filled for each trips in Block 9, Col. 1) .
        /// </summary>
        public static string Block91 {
            get {
                return ResourceManager.GetString("Block91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat/ Dingi .
        /// </summary>
        public static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string Cars1 {
            get {
                return ResourceManager.GetString("Cars1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [4] household characteristics .
        /// </summary>
        public static string characteristics {
            get {
                return ResourceManager.GetString("characteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class of Travel (code) (if code ‘61’ in row 5) .
        /// </summary>
        public static string Class66 {
            get {
                return ResourceManager.GetString("Class66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If code 1 or 2 in col. 8, .
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code or Name of Airport / Railway Station .
        /// </summary>
        public static string Code99 {
            get {
                return ResourceManager.GetString("Code99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether the household possesses any of the following vehicles as on the date of survey for commercial use and number of such vehicles.
        /// </summary>
        public static string commercial {
            get {
                return ResourceManager.GetString("commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost of travel (Rs.) .
        /// </summary>
        public static string cost77 {
            get {
                return ResourceManager.GetString("cost77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destination.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destination .
        /// </summary>
        public static string destination8 {
            get {
                return ResourceManager.GetString("destination8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat/ Dingi .
        /// </summary>
        public static string Dingi {
            get {
                return ResourceManager.GetString("Dingi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance from origin to workplace (kms) .
        /// </summary>
        public static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance from origin to destination (kms).
        /// </summary>
        public static string distance11 {
            get {
                return ResourceManager.GetString("distance11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance from workplace to destination (kms) [for code 1 in col. 10 copy the entry in col. 15 to col. 16] .
        /// </summary>
        public static string distance2 {
            get {
                return ResourceManager.GetString("distance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Name.
        /// </summary>
        public static string district_name {
            get {
                return ResourceManager.GetString("district_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string district3 {
            get {
                return ResourceManager.GetString("district3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district  (code).
        /// </summary>
        public static string district33 {
            get {
                return ResourceManager.GetString("district33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string district66 {
            get {
                return ResourceManager.GetString("district66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string district7 {
            get {
                return ResourceManager.GetString("district7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string district8 {
            get {
                return ResourceManager.GetString("district8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district  (code).
        /// </summary>
        public static string district89 {
            get {
                return ResourceManager.GetString("district89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district (code).
        /// </summary>
        public static string district9 {
            get {
                return ResourceManager.GetString("district9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if entry in col. 4 ≥18,  whether has any driving license as on the date of survey? .
        /// </summary>
        public static string entry {
            get {
                return ResourceManager.GetString("entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name (block letters).
        /// </summary>
        public static string enuname {
            get {
                return ResourceManager.GetString("enuname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for code 1, 2 &amp; 3 in col. 8, whether have at least one fixed place of work outside the premises of dwelling unit at a distance of 1 km or more (yes-1, no-2) .
        /// </summary>
        public static string for_code {
            get {
                return ResourceManager.GetString("for_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for entry≥ 6 in col. 4 and code 4 in col. 8, whether pursuing basic course through correspondence/ distance learning (yes-1, no-2) .
        /// </summary>
        public static string forenrty {
            get {
                return ResourceManager.GetString("forenrty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender (code).
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy vehicles like lorry, truck etc.
        /// </summary>
        public static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time of leaving for destination from origin (hh:mm in 24 hrs format) .
        /// </summary>
        public static string hhmm {
            get {
                return ResourceManager.GetString("hhmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highest level of completed education (code).
        /// </summary>
        public static string highest_level {
            get {
                return ResourceManager.GetString("highest_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to household size .
        /// </summary>
        public static string household {
            get {
                return ResourceManager.GetString("household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col.  12 .
        /// </summary>
        public static string if12 {
            get {
                return ResourceManager.GetString("if12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code between ‘41’ to ‘81’ excluding ‘43’ in col. 5 secondary mode of transport (code) .
        /// </summary>
        public static string if2 {
            get {
                return ResourceManager.GetString("if2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code 2 in col.10 and code 2 in col.11 purpose of trip from workplace to destination (code) .
        /// </summary>
        public static string if3 {
            get {
                return ResourceManager.GetString("if3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string if33 {
            get {
                return ResourceManager.GetString("if33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘11’ in col.17 whether fixed place of work (yes-1, no-2) .
        /// </summary>
        public static string if4 {
            get {
                return ResourceManager.GetString("if4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col.  4.
        /// </summary>
        public static string if5 {
            get {
                return ResourceManager.GetString("if5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col. 3 .
        /// </summary>
        public static string if88 {
            get {
                return ResourceManager.GetString("if88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col.  7 .
        /// </summary>
        public static string if9 {
            get {
                return ResourceManager.GetString("if9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘9’ in col. 6 .
        /// </summary>
        public static string if99 {
            get {
                return ResourceManager.GetString("if99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code ‘2’ in both col. 3 and col.10 whether destination is home (yes-1, no-2)  .
        /// </summary>
        public static string ifcode {
            get {
                return ResourceManager.GetString("ifcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total time taken to canvass the schedule by the team of enumerator (SE/JSO) (in minutes).
        /// </summary>
        public static string inminutes {
            get {
                return ResourceManager.GetString("inminutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if 1 in col., 13, whether used internet for such work (yes- 1, no- 2) .
        /// </summary>
        public static string internet {
            get {
                return ResourceManager.GetString("internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigator Unit Number/Block Number: .
        /// </summary>
        public static string invst_unit_no {
            get {
                return ResourceManager.GetString("invst_unit_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item no..
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item no. .
        /// </summary>
        public static string ItemNo {
            get {
                return ResourceManager.GetString("ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landline number of the household, if any (Start with STD code) .
        /// </summary>
        public static string Landline {
            get {
                return ResourceManager.GetString("Landline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marital status (code).
        /// </summary>
        public static string marital_status {
            get {
                return ResourceManager.GetString("marital_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number of informant/any other household member who can be contacted .
        /// </summary>
        public static string Mobile6 {
            get {
                return ResourceManager.GetString("Mobile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motorcycle or scooter  .
        /// </summary>
        public static string motorcycle {
            get {
                return ResourceManager.GetString("motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Modal (yes-1, no-2) .
        /// </summary>
        public static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name .
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name of informant: .
        /// </summary>
        public static string name6 {
            get {
                return ResourceManager.GetString("name6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the network..
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no. of hh members in the trip .
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of enumerator (SE/JSO) in the team who canvassed the schedule .
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origin to workplace .
        /// </summary>
        public static string origin {
            get {
                return ResourceManager.GetString("origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origin  is home (yes-1, no-2) .
        /// </summary>
        public static string origin1 {
            get {
                return ResourceManager.GetString("origin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origin  .
        /// </summary>
        public static string origin2 {
            get {
                return ResourceManager.GetString("origin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origin .
        /// </summary>
        public static string origin9 {
            get {
                return ResourceManager.GetString("origin9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others .
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others1 {
            get {
                return ResourceManager.GetString("Others1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown) .
        /// </summary>
        public static string PIN1 {
            get {
                return ResourceManager.GetString("PIN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown) .
        /// </summary>
        public static string PIN55 {
            get {
                return ResourceManager.GetString("PIN55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown) .
        /// </summary>
        public static string PIN6 {
            get {
                return ResourceManager.GetString("PIN6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown) .
        /// </summary>
        public static string PIN88 {
            get {
                return ResourceManager.GetString("PIN88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code (give code 9, if PIN is unknown) .
        /// </summary>
        public static string PIN9 {
            get {
                return ResourceManager.GetString("PIN9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number possessed .
        /// </summary>
        public static string possessed {
            get {
                return ResourceManager.GetString("possessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primary mode of transport (code).
        /// </summary>
        public static string primary {
            get {
                return ResourceManager.GetString("primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primary mode of transport (code) .
        /// </summary>
        public static string primary2 {
            get {
                return ResourceManager.GetString("primary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primary mode of transport  (code).
        /// </summary>
        public static string primary33 {
            get {
                return ResourceManager.GetString("primary33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Mode (based on distance) (code) .
        /// </summary>
        public static string Primary99 {
            get {
                return ResourceManager.GetString("Primary99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purpose of trip (code).
        /// </summary>
        public static string purpose {
            get {
                return ResourceManager.GetString("purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for substitution/casualty of the original household .
        /// </summary>
        public static string reason_for_substitution {
            get {
                return ResourceManager.GetString("reason_for_substitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if code between ‘41’ to ‘81’ excluding ‘43’ in col.10, secondary mode of transport (code) [record code 09 if secondary mode of transport is not used]  .
        /// </summary>
        public static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to religion (code) .
        /// </summary>
        public static string religion {
            get {
                return ResourceManager.GetString("religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response code of the informant as assessed by SE/JSO .
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rickshaw/tricycle .
        /// </summary>
        public static string Rickshaw {
            get {
                return ResourceManager.GetString("Rickshaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rickshaw/tricycle .
        /// </summary>
        public static string Rickshawtricycle {
            get {
                return ResourceManager.GetString("Rickshawtricycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Number:.
        /// </summary>
        public static string round_number {
            get {
                return ResourceManager.GetString("round_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Household Number: .
        /// </summary>
        public static string sample_hh_number {
            get {
                return ResourceManager.GetString("sample_hh_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Sub-Unit (SU) Number: .
        /// </summary>
        public static string sample_su_no {
            get {
                return ResourceManager.GetString("sample_su_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Sub-Division Number: .
        /// </summary>
        public static string sample_sub_div_no {
            get {
                return ResourceManager.GetString("sample_sub_div_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save data. Please try again..
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule number: .
        /// </summary>
        public static string sch_no {
            get {
                return ResourceManager.GetString("sch_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motorcycle or scooter .
        /// </summary>
        public static string scooter {
            get {
                return ResourceManager.GetString("scooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Mode of transport (code) .
        /// </summary>
        public static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string sector {
            get {
                return ResourceManager.GetString("sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No. of trip (as in col. 1, block 9) (auto) .
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number of Sample FSU: .
        /// </summary>
        public static string serial_no_sample_fsu {
            get {
                return ResourceManager.GetString("serial_no_sample_fsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to social group (code) .
        /// </summary>
        public static string social {
            get {
                return ResourceManager.GetString("social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. of hh member (as in col. 1, block 3) .
        /// </summary>
        public static string srl {
            get {
                return ResourceManager.GetString("srl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. .
        /// </summary>
        public static string srl_no {
            get {
                return ResourceManager.GetString("srl_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. of trip   (as in col. 1 block 8) .
        /// </summary>
        public static string srl4 {
            get {
                return ResourceManager.GetString("srl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. of hh member who was in that trip (as in col. 1, block 3) .
        /// </summary>
        public static string srl8 {
            get {
                return ResourceManager.GetString("srl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srl. no. of hh member (as in col. 1,block 3) .
        /// </summary>
        public static string srlno {
            get {
                return ResourceManager.GetString("srlno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date .
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT (code).
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT (code).
        /// </summary>
        public static string State_UT {
            get {
                return ResourceManager.GetString("State/UT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/U.T. Name .
        /// </summary>
        public static string state_ut_name {
            get {
                return ResourceManager.GetString("state_ut_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT (code).
        /// </summary>
        public static string State44 {
            get {
                return ResourceManager.GetString("State44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT (code).
        /// </summary>
        public static string State6 {
            get {
                return ResourceManager.GetString("State6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT (code).
        /// </summary>
        public static string State77 {
            get {
                return ResourceManager.GetString("State77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT (code).
        /// </summary>
        public static string State9 {
            get {
                return ResourceManager.GetString("State9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT (code).
        /// </summary>
        public static string StateUT {
            get {
                return ResourceManager.GetString("StateUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/UT(code).
        /// </summary>
        public static string StateUT3 {
            get {
                return ResourceManager.GetString("StateUT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Sub-District/Tehsil/Town .
        /// </summary>
        public static string sub_dist {
            get {
                return ResourceManager.GetString("sub_dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name.
        /// </summary>
        public static string SupervisorName {
            get {
                return ResourceManager.GetString("SupervisorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether possesses as on the date of survey .
        /// </summary>
        public static string survey {
            get {
                return ResourceManager.GetString("survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Code .
        /// </summary>
        public static string survey_code {
            get {
                return ResourceManager.GetString("survey_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  survey/ inspection.
        /// </summary>
        public static string surveyinspection {
            get {
                return ResourceManager.GetString("surveyinspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usual time of leaving for destination from work (hh:mm in 24 hrs format) .
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time of Travel (hours) .
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tractor.
        /// </summary>
        public static string Tractor {
            get {
                return ResourceManager.GetString("Tractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tractor.
        /// </summary>
        public static string Tractor1 {
            get {
                return ResourceManager.GetString("Tractor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip srl. no.
        /// </summary>
        public static string trip {
            get {
                return ResourceManager.GetString("trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip srl. no. .
        /// </summary>
        public static string trip3 {
            get {
                return ResourceManager.GetString("trip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to household type (code) .
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of vehicle .
        /// </summary>
        public static string Typeofvehicle {
            get {
                return ResourceManager.GetString("Typeofvehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usual time of leaving for work from origin (hh:mm in 24 hrs format) .
        /// </summary>
        public static string usual {
            get {
                return ResourceManager.GetString("usual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usual duration of working (in hours).
        /// </summary>
        public static string Usual1 {
            get {
                return ResourceManager.GetString("Usual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van/ minibus/ bus .
        /// </summary>
        public static string Van {
            get {
                return ResourceManager.GetString("Van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type of vehicle .
        /// </summary>
        public static string vehicle {
            get {
                return ResourceManager.GetString("vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether the household possesses any of the following vehicles as on the date of survey for household use and number of such vehicles.
        /// </summary>
        public static string vehicles {
            get {
                return ResourceManager.GetString("vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village Name.
        /// </summary>
        public static string vill_name {
            get {
                return ResourceManager.GetString("vill_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current weekly status  (code).
        /// </summary>
        public static string weeklystatus {
            get {
                return ResourceManager.GetString("weeklystatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether possesses as on the date of survey (yes-1, no-2) .
        /// </summary>
        public static string whether {
            get {
                return ResourceManager.GetString("whether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether return trip performed (yes-1, no-2) .
        /// </summary>
        public static string whether10 {
            get {
                return ResourceManager.GetString("whether10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether travelled to and from the fixed workplace on the travel-day prior to the date of survey (yes-1, no-2)  .
        /// </summary>
        public static string whether2 {
            get {
                return ResourceManager.GetString("whether2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether any remark has been entered by SE/JSO/SS/SSO In block 10/11 (yes -1, no -2).
        /// </summary>
        public static string whether23 {
            get {
                return ResourceManager.GetString("whether23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether any remark has been entered by SE/JSO/SS/SSO Elsewhere in the schedule (yes -1, no -2).
        /// </summary>
        public static string Whether24 {
            get {
                return ResourceManager.GetString("Whether24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether round trip performed (yes-1, no-2) .
        /// </summary>
        public static string whether3 {
            get {
                return ResourceManager.GetString("whether3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whether worked from home in the current status during last 30 days (yes – 1, no – 2) .
        /// </summary>
        public static string worked {
            get {
                return ResourceManager.GetString("worked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workplace to destination.
        /// </summary>
        public static string workplace {
            get {
                return ResourceManager.GetString("workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workplace .
        /// </summary>
        public static string workplace3 {
            get {
                return ResourceManager.GetString("workplace3", resourceCulture);
            }
        }
    }
}
